version: '3.8'

services:
  restaurant-service:
    build: .
    container_name: restaurant-management-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_APPLICATION_NAME=restaurantManagementService
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:restaurantdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8084
    restart: unless-stopped
